name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
          
      # Instalar dependencias
      - name: Install dependencies
        working-directory: ./api/
        run: npm install        
          
      # Executar build        
      - name: Run build
        working-directory: ./api/
        run: npm run build
        
      # Copiar pasta dist para dentro do server
      - name: Copy dist to server        
        uses: appleboy/scp-action@master        
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          working-directory: ./api/
          source: "."
          target: "~/apps/gobarber-fullstack/api/"
         
      # Substituir o código da pasta dist pelo novo
      # Executar npm install no server
      # Executar migrations
      # Restart no servidor
      
